FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="Backend Development image for the Memories-MicroService App"

WORKDIR /app
COPY ["package.json","package-lock.json", "./"]
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install -g nodemon
RUN npm install
USER node
COPY --chown=node:node . /app

COPY . .

EXPOSE 5000

CMD [ "npm", "run", "comment_microservice" ]