FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="Frontend Development image for the Memories-MicroService App"

USER node
WORKDIR /app

COPY ./package.json ./
COPY --chown=node:node . /app

RUN npm install

ARG REACT_APP_CLIENT_ID

ENV REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start" ]